### ISSUE TITLE
Comparison with pcre2el?

### ISSUE THREAD

**Issue by alphapapa** [mattiase/xr#1]
Hi,

Thanks for this package, it looks cool.  There also exists https://github.com/joddie/pcre2el, which seems to do the same thing, among other features.  Would you explain what the differences are in this functionality, and how `xr` may do the RE->`rx` conversion better?  It would be good to put that in the readme.

**Comment by mattiase** [comment]
Thank you, the package comment already had some text which has now been copied to README.org.
pcre2el appears to be a fine package but is probably unmaintained. However, the packages have different scopes; xr is likely to be more accurate in the overlapping functionality.
Of course, this could change if someone starts maintaining pcre2el again.

**Comment by alphapapa** [comment]
I wonder if it would be good to put the regexp->rx conversion into `rx.el` in Emacs itself, then other packages could use the same functionality instead of having multiple implementations with slight differences.  What do you think?

**Comment by mattiase** [comment]
Other packages can still use xr by adding a dependency. Since xr is in GNU ELPA, it is easily installed. For example, the relint package uses the mistake-finding functions in xr, and installing relint automatically installs xr by the Emacs package manager.
