### ISSUE TITLE
False positive of "Repetition subsumed by preceding repetition" warning

### ISSUE THREAD

**Issue by OGAWAHirofumi** [mattiase/xr#2]
With the following:
```elisp
(xr-lint ".*? *\\([^,]*\\)")
=> ((4 . "Repetition subsumed by preceding repetition"))
```

xr warns about ".\*\? *". But "non-greedy repetition" + "greedy repetition" pattern
should be legitimate usage.

The following is simplified usage.

```elisp

(let ((str "foo, bar"))
  (with-temp-buffer
    (insert str)
    (looking-back "^.*?\\([^,]*\\)")
    (match-string 1))
  => " bar"
  (with-temp-buffer
    (insert str)
    (looking-back "^.*? *\\([^,]*\\)")
    (match-string 1))
  => "bar"
  )
```

**Comment by mattiase** [comment]
Thank you for the report! You are quite right, a greedy repetition cannot be subsumed by a non-greedy one. I have now added the required logic. It may take a day or so for the change to make its way to ELPA; I hope that is not too much of a problem.
