### ISSUE TITLE
Do not distribute xr-test.el and .github as part of ELPA package

### ISSUE THREAD

**Issue by minad** [mattiase/xr#4]
Hi, thank you for this package! I noticed that the ELPA distribution contains the test file and the .github configuration directory. I propose to exclude these files from the distribution. Packages usually don't distribute their tests.

**Comment by mattiase** [comment]
Thank you, yes, it seems reasonable to exclude nonessential files from the distribution. Does it make sense to exclude the Makefile as well? I don't think it is used by the installation, is it?

I presume the `:ignored-files` clause in `elpa-packages` is where to specify this.

**Comment by minad** [comment]
Oh yes, the Makefile should be ignored too. I missed this. `:ignored-files` is the way to go, there are a few examples in the `elpa-packages` file.

**Comment by mattiase** [comment]
Done. Does it take effect by itself or do I have to release a new package version for that to happen?
If the latter, is there a way to force it?

**Comment by minad** [comment]
As far as I know the package versions are immutable, so I would bump the patch/minor version number for ELPA to create a new package.

**Comment by mattiase** [comment]
All right. I have no reason for making a new version right now but one will surely be forthcoming eventually and things will take care of themselves.
