### ISSUE TITLE
native-ice error in native compilation

### ISSUE THREAD

**Issue by jian-lin** [mattiase/xr#9]
```
libgccjit.so: error: gcc_jit_context_new_call_through_ptr: too many arguments to fn_ptr: freloc->R736f7274_sort_0 (got 5 args, expected 2)

Error: native-ice ("/nix/store/hash-emacs-xr-2.0/share/emacs/site-lisp/elpa/xr-2.0/xr.el" "gcc_jit_context_new_call_through_ptr: too many arguments to fn_ptr: freloc->R736f7274_sort_0 (got 5 args, expected 2)")
```

full log: https://hydra.nixos.org/build/271413217/nixlog/1

**Comment by mattiase** [comment]
That doesn't look like a problem with xr; `native-ice` is an internal error of the native compiler. More likely it's a configuration problem.

**Comment by douo** [comment]
Encountering the same issue in vanilla Emacs, reproducible on both macOS and Linux.
> Warning (comp): /home/x/.emacs.d/straight/build/xr/xr.el: Error: Internal native compiler error gcc_jit_context_new_call_through_ptr: too many arguments to fn_ptr: freloc->R736f7274_sort_0 (got 5 args, expected 2)

**Comment by mattiase** [comment]
Thank you, but an internal compiler error indicates a bug in the compiler, not xr. Consider reporting it to `bug-gnu-emacs@gnu.org`.
